### ISSUE TITLE
Error when trying to run the script

### ISSUE THREAD

**Issue by kabesama** [Kozova1/Parsec-Integration-With-RetroPie#1]
Hello!
When I type in "sudo bash setup.sh", this happens
![retropie parsec1](https://user-images.githubusercontent.com/17355980/29237315-1d678f8a-7f1c-11e7-9ddc-8f79d775917d.png)

I've checked, and I do have a ports-directory. I have kodi installed in that directory at the moment.
Can you help me?

**Comment by Kozova1** [comment]
Contact me by discord and I will try to help you.
Kozova1 #1926
