### ISSUE TITLE
Error when trying to launch Parsec

### ISSUE THREAD

**Issue by jsavilisky** [Kozova1/Parsec-Integration-With-RetroPie#25]
I am new to parsec and retropie. I followed the instructions and when I type in 'parsec' or 'sudo parsec' i get "-bash: parsec: command not found. I did see that there is a 'parsec' option where the other emulators are. when I try to launch it that way I get the very brief message:
"/home/pi/RetroPie/roms/parsec/Parsec.sh: line 3: warning: here-document at line 1 delimited by the end-of-file (wanted 'EOFy')
/home/pi/RetroPie/roms/parsec/Parsec.sh: line 1: parsec: command not found"

Not sure where to go from here. 
I am using a Raspberry Pi 3b+ 
The only changes I have made are to expand the file system and to enable SSH.
I have not even installed any rooms yet

**Comment by rostad360** [comment]
I have the same problem, followed the guide and followed a youtube video. No luck. just says that the command is not found ....

**Comment by Kozova1** [comment]
Try to just install parsec manually

**Comment by jacksaturn** [comment]
The solution for me was to edit /home/pi/RetroPie/roms/parsec/Parsec.sh and change "parsec" to "parsecd". For whatever reason, Parsec will only launch on my Raspberry Pi using the parsecd command.

**Comment by lucasfais** [comment]
Same issue here. I tried to run `parsecd` instead of `parsec`, it prints "Compiled" twice, but it never asks me for user and password. That happens with both installation options.

**Comment by jacksaturn** [comment]
@lucasfais Are you viewing your Raspberry Pi with a directly-connected monitor or via VNC?

**Comment by lucasfais** [comment]
🤔 I was actually connected via SSH. I thought it would ask for user/password in the command line... I'll try again later using a graphical interface. Thank you.

**Comment by jacksaturn** [comment]
@lucasfais Yep, in my experience, VNC or SSH both won't reveal the graphical Parsec window. I recognized your issue with seeing "Compiled" twice followed by nothing; in my case it was because VNC couldn't display the image. Turned out Parsec was running, and visible on the monitor hooked directly to the Pi once I checked!

**Comment by franoscutaro** [comment]
Can we get an updated setup guide? That would be awesome. I'm stuck with the double "Compiled" message after typing "parsecd" instead of "parsec" ( I've got the "pasec command not found" error after installing everything ).

Thank you very much for making this integration with retropie :D

**Comment by jacksaturn** [comment]
@franoscutaro Any chance you're trying to run Parsec while connected via SSH or VNC?

**Comment by franoscutaro** [comment]
@jacksaturn Yes I am. I'm connected via SSH in order to run the commands.

Your question makes me think, though. Should I quit Emulation Station and run the command in the PI's terminal? That way I can avoid connecting via SSH.

Thanks for your answer!

**Comment by jacksaturn** [comment]
@franoscutaro The reason I asked is because I explained the issue in the reply right before yours in this thread. 😊

To anyone else reading this thread from here on out: if you're trying to run parsec or parsecd via SSH or VNC, you'll see "Compiled" twice, but no graphics. If you connect a monitor (or view the already connected monitor) on your Pi, however, you'll see that Parsec is running there. You just aren't able to see it via your remote connection.

**Comment by franoscutaro** [comment]
@jacksaturn Hey thanks for your answer and yes, I saw your previous comment. And I'm asking for some updated guide that can include that info so everyone can see it outside the issues section :)

Thanks for your help.

**Comment by Kozova1** [comment]
I'm unfortunately very busy and don't have the time to update the guide. However, if you submit a pull request I'll look at it and approve it (If it's of decent quality).

**Comment by Eiscoffee** [comment]
Okay guys, this is how it worked for me (thanks to @jacksaturn ):

1. open the filemanager in RetroPie
2. navigate into: /home/pi/RetroPie/roms/parsec/
3. edit the Parsec.sh
5. select your favorite editor (I take nano)
6. edit the lines into:
parsecd server_id=your_host_server_id << EOF your_host_server_id 
y
1
EOF

finished

**Comment by Kozova1** [comment]
I believe I fixed the bug, also if you do take the answer above, don't do part 3, it shouldn't be necessary

**Comment by duckpuppy** [comment]
It looks like you updated setup.sh but not port_setup.sh

**Comment by Kozova1** [comment]
I think that this can be closed now
