### ISSUE TITLE
No such option as "Remember me"

### ISSUE THREAD

**Issue by pugshot** [Kozova1/Parsec-Integration-With-RetroPie#26]
Parsec is working fine on Pi 3 B+'s Retropie. I had a few problems where I installed it as per instructions, but for some reason I had to run it with "parsecd" so that also required me to fiddle with the files and rename every "parsec" to "parsecd" to get it to work. No clue why this happened since I followed the readme to the letter. Anyway, upon logging in with email and password, there is no "remember me" option anywhere. I can't auto-login if I reboot retropie, and I have to login to parsec every time. What could be the issue?

**Comment by Eiscoffee** [comment]
As far as I recognized you stay logged in even after reboot. I dont have a remember me option either but it works without it. Do you start parsec with the console or in retropie UI?

**Comment by Kozova1** [comment]
I think they removed the remember me option

**Comment by Kozova1** [comment]
I think that this issue can be closed now.
