### ISSUE TITLE
No command parsec after install

### ISSUE THREAD

**Issue by Mxater** [Kozova1/Parsec-Integration-With-RetroPie#27]
**Describe the bug**
Command parsec not found after install

**To Reproduce**
1. After install

**Screenshots**

![imagen](https://user-images.githubusercontent.com/4630666/88469839-70860f80-cec3-11ea-9562-72005ba6766e.png)

**Desktop (please complete the following information):**
 - OS: Linux 4.19.97-v7l+ armv7l GNU/Linux
- Raspberry 4 pi b+

**Comment by Kozova1** [comment]
Try `parsecd` instead
