### ISSUE TITLE
parsec command not found

### ISSUE THREAD

**Issue by Frettarix** [Kozova1/Parsec-Integration-With-RetroPie#28]
After running the setup.sh it cannot find the 'parsec' command, it can find the parsecd command but thats a GUI one and it crashes Retropie after connecting to the host.

**Comment by gnunesmoura** [comment]
I'm facing the same issue.

**Comment by Frettarix** [comment]
I also tried using parsecd, which works. But then when I actually log in the entire thing glitches and the retropie's screen will be black untill this guest user is kicked from parsec.

I tried changing the memory from 256 to 128 and 320, no difference.

**Comment by Kozova1** [comment]
Please try to completely remove and install it again, the new version should (hopefully) work

**Comment by Frettarix** [comment]
Hi again,

I did as suggested. So now no more error that the command ain't found, but it still gives a black screen. The moment I connect, my audio gets redirected to parsec it seems, but the video gives a quick crash-like cut to black. When kicking the parsec guest from the host system the screen returns to normal and retropie functions properly again.

**Comment by Kozova1** [comment]
I see. Is this a RPi 4? if so, as far as I know it's not supported by Parsec. If not, try to contact Parsec support and tell them that you have the black screen issue. It's not related to my script.

**Comment by Frettarix** [comment]
It's an RPi 3, did not test the 4 yet. It's a basic installation of retropie, updated, and then ran your script, I'll request help from parsec :)

**Comment by Frettarix** [comment]
After investigating this further it has to do with the resolution of the host computer, altering the resolution of the host computer should resolve the issue.
