### ISSUE TITLE
No directory found

### ISSUE THREAD

**Issue by michelroberge** [Kozova1/Parsec-Integration-With-RetroPie#3]
when running setup, I got an error No such file / directory not found. Now my systems.cfg file is gone.

**Comment by Crashdummyy** [comment]
Did you sudo ?
This Command `sudo mv --force /opt/retropie/configs/all/emulationstation/es_systems.cfg /opt/retropie/configs/all/emulationstation/es_systems.cfg.backup` saves your config.
You can easily Restore it by Reverting the Arguments:
 `sudo mv --force /opt/retropie/configs/all/emulationstation/es_systems.cfg.backup /opt/retropie/configs/all/emulationstation/es_systems.cfg`

**Comment by michelroberge** [comment]
I did sudo. I reverted. Maybe it's because it conflicted with Moonlight? Parsec was in the backup, moonlight was gone, and es_systems.cfg was gone too. Only the backup file remained.

**Comment by Erick8x** [comment]
I have the same error, but my systems.cfg remains intact. Idk what the problem, but moonlight doesn't having conflict with the new version of RetroPie?
