### ISSUE TITLE
[question] Raspberry Pi version support

### ISSUE THREAD

**Issue by ivdimitro** [Kozova1/Parsec-Integration-With-RetroPie#30]
Hi, In the how to you have mentioned that this supports only Raspberry Pi. Which version did you have in mind - 3 or 4? 
AFIK Raspberry Pi 4 is not supported by parsek so it would be interesting to know if you managed to make it work.
Thanks.

**Comment by Kozova1** [comment]
If parsec doesn't run on the pi4 then it can't run my program, sorry.
