### ISSUE TITLE
Controller Pass through

### ISSUE THREAD

**Issue by UltimaQ** [Kozova1/Parsec-Integration-With-RetroPie#31]
Currently I am unable to pass through my controllers from within retropie to Parsec. 
Both my host PC and my RPI are using the 150-47 build of parsec. 
My Controller is functioning within RetroPie and can be used when selecting my host PC. 
Once i am in the host box i cannot seem to control anything or setup my controller on my emulators. It is also not registered within windows once connected either. 

I have both the xpad and xbox360 drivers installed on retropie and ViGem on the host. 
I'm fairly new to retropie so any tips or tricks will help.

**Comment by Kozova1** [comment]
Does controller passthrough work when you use Parsec outside of retropie?  
If not, it's probably not a problem with retropie but with the driver/parsec itself.

**Comment by jenn334** [comment]
> Does controller passthrough work when you use Parsec outside of retropie?
> If not, it's probably not a problem with retropie but with the driver/parsec itself.
