### ISSUE TITLE
Window Failure

### ISSUE THREAD

**Issue by SanchesDaniel** [Kozova1/Parsec-Integration-With-RetroPie#32]
I to try use parsec in raspberry pi 4 using retropi 4.6 but when i start the program shows an error .

line 3: warning: here-document at line 1 delimited by end-of-file (wanted `EOFy')
[D 2020-09-30 22:44:33] SDL_CreateWindow=0

[Window Failure]
--------------------
Parsec could not create the main window.
Please contact us if this problem persists.

**Comment by Kozova1** [comment]
Raspberry Pi 4 is not supported by parsec afaik.
