### ISSUE TITLE
[Question] How to return to emulationstation?

### ISSUE THREAD

**Issue by dconz13** [Kozova1/Parsec-Integration-With-RetroPie#33]
Hey nice work setting this up! As I wrote in the title, how do you exit from Parsec to return to the emulation station menu? I tried all the button combos i could think of on a controller and keyboard.

Adding this info to the ReadMe would be super helpful.

**Comment by xayhewalo** [comment]
`` Ctrl+Alt+` ``

Also, how to exit a stream is in the [Parsec documentation](https://support.parsecgaming.com/hc/en-us/articles/115003632451-Parsec-Shortcuts)
