### ISSUE TITLE
Logging in to parsec

### ISSUE THREAD

**Issue by ItsASam** [Kozova1/Parsec-Integration-With-RetroPie#6]
When I try to use parsec on RetroPie it gives me the error 2001, I looked it up and saw that means I'm not logged in. My question is how do I log in?

**Comment by Ratirefure** [comment]
open terminal (F4) and just type "Parsec" (no quotes) and it'll prompt you for your email and password, then it'll ask which computer you wanna connect to. this seems to be a one-time thing, it'll just pair to that computer and you'll be able to just run Parsec from the RetroPie gui every time after that.
