### ISSUE TITLE
Black screen when connected to a host

### ISSUE THREAD

**Issue by erikbrick** [Kozova1/Parsec-Integration-With-RetroPie#8]
Whenever I try connect to a host on my retropie, it just shows a black screen even though on the host it says that I am connected.

**Comment by Kozova1** [comment]
does the same thing happen when launching parsec through command line?

**Comment by erikbrick** [comment]
It doesn't work at all without the command line, and when I use the command line the black screen appears

**Comment by Kozova1** [comment]
you should guys at parsec support because black screen is a common issue
