### ISSUE TITLE
Error -2001

### ISSUE THREAD

**Issue by rickasheye** [Kozova1/Parsec-Integration-With-RetroPie#9]
this is the error i got launching parsec from emulation station

**Comment by rickasheye** [comment]
it said there was an error parsing ']' i think i cant remember also the images are missing from emulation station
im using a raspberry pi 3 Model B no +

**Comment by Kozova1** [comment]
you need to launch parsec once through the command line, login with your account and select remember me.

also, re-download the script and run it again, and this time don't write the server ID like this: [12345] but like this: 12345

**Comment by dsandler** [comment]
if you're actually getting error `-1002` this just means you need to run the other side of parsec (start parsec up on your cloud instance or home PC).

**Comment by Kozova1** [comment]
Ok so first, re-image your pi
then install the script again using the new instructions.
finally run parsec once without the script and select "remember me"

**Comment by rickasheye** [comment]
i have fixed it the pi wouldnt connect to the internet thanks guys
